[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Add this section to serve static files from the test folder
[[redirects]]
  from = "/test/*"
  to = "/test/:splat"
  status = 200

# Add this section to serve video files
[[redirects]]
  from = "/videos/*"
  to = "/videos/:splat"
  status = 200

# Add redirects for portfolio page variations
[[redirects]]
  from = "/portofolio"
  to = "/portfolio"
  status = 301

[[redirects]]
  from = "/Portofolio"
  to = "/portfolio"
  status = 301

[[redirects]]
  from = "/PORTOFOLIO"
  to = "/portfolio"
  status = 301

# Catch-all redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"