[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Add this section to serve static files from the test folder
[[redirects]]
  from = "/test/*"
  to = "/test/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"